const TRANSACTION_STATUS = {
  STANDARD: "STANDARD",
  PENDING_APPROVAL: "PENDING_APPROVAL",
  APPROVED_PENDING_BILL: "APPROVED_PENDING_BILL",
  APPROVED_COMPLETED: "APPROVED_COMPLETED",
  REJECTED: "REJECTED",
};

module.exports = TRANSACTION_STATUS;